### ISSUE TITLE
[scoping/idea] Passthrough instead of selling any badger sett tokens from our staking optimizer factory

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/vested-aura#11]
Story:  @MrrPo  would like to start bribing WBTC/BADGER instead of BADGER.  We think other DAOs would prefer us to not dump their bribes as well.  By emitting auto-compounding vault tokens, we provide DAOs with a way to bribe and not have us sell.

Technical Implementation
The idea perhaps works best as a whitelist of sett tokens that are not sold but instead passed through directly passed through to the tree like BADGER.  Badger could also be a member of this list.  Note that the tokens should be added/removed by governance in order to ensure that only tokens that are bribed a lot and don't create poor and dusty UX are emitted.

Other Considerations:
Hidden Hands needs pricing for these tokens for their UI and autobriber.  They have stated they would consider pulling from our API, but currently use coingecko.  We can also create small LP pools  for price discovery for these tokens and add them to coingecko to remove dependancy on our API if desired by badger or redacted.

Timeline:
There is currently not a clear decision to do bribe with sett tokens or whitelisted tokens, but a this seems likely to be used if available in the not so distant future.

**Comment by MrrPo** [comment]
`We think other DAOs would prefer us to not dump their bribes as well.`
I don't think it's viable for the vault product. 
We don't want to step outside the three-token model and distribute some other token dust to the vault depositors. 
So my request comes down exclusively to Badger/WBTC LP. Using graviAURA and bauraBAL for bribes would be all right, but nothing besides that.

**Comment by Tritium-VLK** [comment]
> `We think other DAOs would prefer us to not dump their bribes as well.` I don't think it's viable for the vault product. We don't want to step outside the three-token model and distribute some other token dust to the vault depositors. So my request comes down exclusively to Badger/WBTC LP. Using graviAURA and bauraBAL for bribes would be all right, but nothing besides that.

We can start the whitelist with only BADGER and the bBADGER/WBTC80/20 token and discuss the rest later.  I don't think it changes the scope/tech spec much.

**Comment by GalloDaSballo** [comment]
Solved by 1.2

See
https://github.com/Badger-Finance/Badger-Project-Planning/issues/79
